# Generated by Django 3.1.2 on 2020-10-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_logged_in',
        ),
    ]
