# Generated by Django 3.1.2 on 2020-10-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
